# Generated by Django 2.2.6 on 2019-11-14 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bebidas', '0001_initial'),
        ('funcionarios', '0001_initial'),
        ('lanches', '0001_initial'),
        ('clientes', '0001_initial'),
        ('adicionais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False)),
                ('dataPedido', models.DateTimeField(default=datetime.datetime.now)),
                ('dataFinalPedido', models.DateTimeField(default=datetime.datetime.now)),
                ('isDelivery', models.BooleanField(default=False)),
                ('mesa', models.CharField(max_length=5)),
                ('estadoPedido', models.CharField(max_length=50)),
                ('totalpedido', models.DecimalField(decimal_places=2, max_digits=4)),
                ('isKitchenRequest', models.BooleanField(default=False)),
                ('isBarRequest', models.BooleanField(default=False)),
                ('kitchenFinishing', models.BooleanField(default=False)),
                ('bartenderFinishing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pedidoAdicional', models.ManyToManyField(to='adicionais.Adicional')),
                ('pedidoBebida', models.ManyToManyField(to='bebidas.Bebida')),
                ('pedidoCliente', models.ManyToManyField(to='clientes.Cliente')),
                ('pedidoFuncionarios', models.ManyToManyField(to='funcionarios.Funcionario')),
                ('pedidoLanche', models.ManyToManyField(to='lanches.Lanche')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['dataPedido'],
            },
        ),
    ]
