# Generated by Django 2.2.6 on 2019-11-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='pedidoFuncionario',
            new_name='pedidoGarcon',
        ),
    ]
