# Generated by Django 2.2.6 on 2019-10-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adicionais', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pedidoAdicional',
            field=models.ManyToManyField(to='adicionais.Adicional'),
        ),
    ]
