# Generated by Django 2.2.6 on 2019-11-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('pedidos', '0002_auto_20191107_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pedidoGarcon',
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedidoFuncionarios',
            field=models.ManyToManyField(to='funcionarios.Funcionario'),
        ),
    ]
