# Generated by Django 2.2.6 on 2019-11-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20191107_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='isDelivery',
            field=models.BooleanField(default=False),
        ),
    ]
