# Generated by Django 2.2.6 on 2019-11-14 13:36

import apps.bebidas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('idBebida', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(default='texto')),
                ('preco', models.DecimalField(decimal_places=5, max_digits=10)),
                ('isAlcoolico', models.BooleanField(default=True)),
                ('quantidade', models.IntegerField()),
                ('foto', models.ImageField(default='sem-imagem-avatar.png', upload_to=apps.bebidas.models.user_directory_path)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bebida',
                'verbose_name_plural': 'Bebidas',
                'ordering': ['nome'],
            },
        ),
    ]
