# Generated by Django 2.2.6 on 2019-11-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebida',
            name='isAlcoolico',
            field=models.BooleanField(default=True),
        ),
    ]
