# Generated by Django 2.2.6 on 2019-10-17 02:23

import apps.bebidas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='foto',
            field=models.ImageField(default='sem-imagem-avatar.png', upload_to=apps.bebidas.models.user_directory_path),
        ),
    ]
