# Generated by Django 2.2.6 on 2019-11-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0002_auto_20191105_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebida',
            name='preco',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
