# Generated by Django 2.2.6 on 2019-10-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0002_bebida_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='quantidade',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=4),
        ),
    ]
