# Generated by Django 2.2.6 on 2019-11-14 13:36

import apps.lanches.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lanche',
            fields=[
                ('idLanche', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(default='')),
                ('preco', models.DecimalField(decimal_places=5, max_digits=10)),
                ('foto', models.ImageField(default='sem-imagem-avatar.png', upload_to=apps.lanches.models.user_directory_path)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lanche',
                'verbose_name_plural': 'Lanches',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LancheIngredientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredientes.Ingrediente')),
                ('lanche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lanches.Lanche')),
            ],
        ),
        migrations.AddField(
            model_name='lanche',
            name='lancheIngrediente',
            field=models.ManyToManyField(through='lanches.LancheIngredientes', to='ingredientes.Ingrediente'),
        ),
    ]
