# Generated by Django 2.2.6 on 2019-10-17 02:23

import apps.lanches.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanche',
            name='foto',
            field=models.ImageField(default='sem-imagem-avatar.png', upload_to=apps.lanches.models.user_directory_path),
        ),
    ]
