# Generated by Django 2.2.6 on 2019-11-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanche',
            name='preco',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
