# Generated by Django 2.2.6 on 2019-10-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0001_initial'),
        ('lanches', '0002_lanche_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanche',
            name='lancheIngrediente',
            field=models.ManyToManyField(to='ingredientes.Ingrediente'),
        ),
    ]
