# Generated by Django 2.2.6 on 2019-10-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adicionais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicional',
            name='isFalta',
            field=models.BooleanField(default=False),
        ),
    ]
