# Generated by Django 2.2.6 on 2019-10-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('adicionais', '0002_adicional_isfalta'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicional',
            name='ingredienteFornecedor',
            field=models.ManyToManyField(to='fornecedores.Fornecedor'),
        ),
    ]
