# Generated by Django 2.2.6 on 2019-10-21 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adicionais', '0003_adicional_ingredientefornecedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adicional',
            old_name='ingredienteFornecedor',
            new_name='adicionalFornecedor',
        ),
    ]
