# Generated by Django 2.2.6 on 2019-10-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='quantidade',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=4),
        ),
    ]
