# Generated by Django 2.2.6 on 2019-10-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0002_auto_20191020_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='isFalta',
            field=models.BooleanField(default=False),
        ),
    ]
