# Generated by Django 2.2.6 on 2019-10-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0004_ingrediente_ingredientefornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
